on:
  workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::947418573212:role/github
          aws-region: us-east-1
      # Upload a file to AWS s3
      - name: test
        run: |
          aws sts get-caller-identity
